using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using com.hexengine.gear.editor;

namespace com.hexengine.gear.parameters.editor {
	internal static class ParcelableGenerator {
		internal static void Generate(System.Type type) {
			HexengineProject.CreateTextFile(
				$"parameters{Path.DirectorySeparatorChar}Scripts{Path.DirectorySeparatorChar}parcelables{Path.DirectorySeparatorChar}{type.Name}.cs", 
				writer => { Write(writer, type); }
			);
		}

		internal static void GenerateTable(System.Type type) {
			HexengineProject.CreateTextFile(
				$"parameters{Path.DirectorySeparatorChar}Editor{Path.DirectorySeparatorChar}tables{Path.DirectorySeparatorChar}{type.Name}Table.cs",
				writer => { WriteTable(writer, type); }
			);
		}

		private static void Write(StreamWriter writer, System.Type type) {
			List<string> namespaces = new List<string>();
			namespaces.Add("com.hexengine.gear.parameters");
			namespaces.Add("System.IO");
			if (type.GetCustomAttribute<Parcelize>() is Parcelize parcelize) {
				foreach(string ns in parcelize.namespaces) {
					if(! namespaces.Contains(ns)) { namespaces.Add(ns); }
				}
			}

			writer.WriteLine($"// Auto-generated by `ParcelableGenerator.Generate()`");
			writer.WriteLine();
			namespaces.Sort();
			foreach(string useNamespace in namespaces) {
				writer.WriteLine($"using {useNamespace};");
			}
			writer.WriteLine();
			writer.WriteLine($"namespace {type.Namespace} {{");
			string typeSeries = type.IsClass ? "class" : "struct";
			writer.WriteLine($"\tpublic partial {typeSeries} {type.Name} : Parcelable {{");

			writer.WriteLine($"\t\tpublic void LoadFromBytes(byte[] bytes, ref int index, System.Text.Encoding encoding) {{");

			BindingFlags flags =
				BindingFlags.Instance |
				BindingFlags.Public |
				BindingFlags.NonPublic |
				BindingFlags.FlattenHierarchy;
			FieldInfo[] fields = type.GetFields(flags);
			foreach (FieldInfo field in fields) {
				System.Type fieldType = field.FieldType;
				if(fieldType.IsArray) {
					System.Type elementType = fieldType.GetElementType();
					writer.WriteLine();
					if (elementType == typeof(string)){
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new string[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\tint textLength = System.BitConverter.ToInt32(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(int);");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = encoding.GetString(bytes, index, textLength);");
						writer.WriteLine($"\t\t\t\t\tindex += textLength;");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(bool)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new bool[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToBoolean(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(bool);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(int)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new int[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToInt32(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(int);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(uint)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new uint[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToUInt32(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(uint);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(long)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new long[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToInt64(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(long);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(ulong)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new ulong[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToUInt64(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(ulong);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(float)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new float[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToSingle(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(float);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType == typeof(double)) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new double[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = System.BitConverter.ToDouble(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(double);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType.IsEnum) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new {elementType.Name}[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = ({elementType.Name})System.BitConverter.ToInt32(bytes, index);");
						writer.WriteLine($"\t\t\t\t\tindex += sizeof(int);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					} else if (elementType.GetCustomAttribute<Parcelize>() != null) {
						writer.WriteLine($"\t\t\t{{");
						writer.WriteLine($"\t\t\t\tshort arraySize = System.BitConverter.ToInt16(bytes, index);");
						writer.WriteLine($"\t\t\t\tindex += sizeof(short);");
						writer.WriteLine($"\t\t\t\t{field.Name} = new {elementType.Name}[arraySize];");
						writer.WriteLine($"\t\t\t\tfor(short i = 0; i < arraySize; ++i) {{");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i] = new {elementType.Name}();");
						writer.WriteLine($"\t\t\t\t\t{field.Name}[i].LoadFromBytes(bytes, ref index, encoding);");
						writer.WriteLine($"\t\t\t\t}}");
						writer.WriteLine($"\t\t\t}}");
					}
				} else if (fieldType == typeof(string)){
					writer.WriteLine($"\t\t\t{{");
					writer.WriteLine($"\t\t\t\tint textLength = System.BitConverter.ToInt32(bytes, index);");
					writer.WriteLine($"\t\t\t\tindex += sizeof(int);");
					writer.WriteLine($"\t\t\t\t{field.Name} = encoding.GetString(bytes, index, textLength);");
					writer.WriteLine($"\t\t\t\tindex += textLength;");
					writer.WriteLine($"\t\t\t}}");
				} else if(fieldType.IsPrimitive) {
					if (fieldType == typeof(bool)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToBoolean(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(bool);");
					} else if (fieldType == typeof(int)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToInt32(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(int);");
					} else if (fieldType == typeof(uint)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToUInt32(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(uint);");
					} else if (fieldType == typeof(long)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToInt64(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(long);");
					} else if (fieldType == typeof(ulong)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToUInt64(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(ulong);");
					} else if (fieldType == typeof(float)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToSingle(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(float);");
					} else if (fieldType == typeof(double)) {
						writer.WriteLine($"\t\t\t{field.Name} = System.BitConverter.ToDouble(bytes, index);");
						writer.WriteLine($"\t\t\tindex += sizeof(double);");
					}
				} else if (fieldType.IsEnum) {
					writer.WriteLine($"\t\t\t{field.Name} = ({fieldType.Name})System.BitConverter.ToInt32(bytes, index);");
					writer.WriteLine($"\t\t\tindex += sizeof(int);");
				} else if (fieldType.GetCustomAttribute<Parcelize>() != null) {
					writer.WriteLine($"\t\t\t{field.Name} = new {field.FieldType.Name}();");
					writer.WriteLine($"\t\t\t{field.Name}.LoadFromBytes(bytes, ref index, encoding);");
				}
			}
			writer.WriteLine($"\t\t}}");

			writer.WriteLine();
			writer.WriteLine($"\t\tpublic void AppendToBytes(BinaryWriter writer, out int dataSize, System.Text.Encoding encoding) {{");
			writer.WriteLine($"\t\t\tdataSize = 0;");
			foreach(FieldInfo field in fields) {
				System.Type fieldType = field.FieldType;
				if (fieldType.IsArray) {
					System.Type elementType = fieldType.GetElementType();
					writer.WriteLine($"\t\t\twriter.Write((short){field.Name}.Length);");
					writer.WriteLine($"\t\t\tdataSize += {sizeof(short)};");
					if (elementType == typeof(string)) {
						writer.WriteLine($"\t\t\tfor(int i = 0; i < {field.Name}.Length; ++i) {{");
						writer.WriteLine($"\t\t\t\tbyte[] bytes = encoding.GetBytes({field.Name}[i]);");
						writer.WriteLine($"\t\t\t\twriter.Write(bytes.Length);");
						writer.WriteLine($"\t\t\t\twriter.Write(bytes);");
						writer.WriteLine($"\t\t\t\tdataSize += bytes.Length + {sizeof(int)};");
						writer.WriteLine($"\t\t\t}}");
					}
					else if(elementType.IsPrimitive) {
						if(
							elementType == typeof(bool) ||
							elementType == typeof(int) ||
							elementType == typeof(uint) || 
							elementType == typeof(long) ||
							elementType == typeof(ulong) ||
							elementType == typeof(double) ||
							elementType == typeof(float)
						) {
							writer.WriteLine($"\t\t\tfor(int i = 0; i < {field.Name}.Length; ++i) {{");
							writer.WriteLine($"\t\t\t\twriter.Write({field.Name}[i]);");
							writer.WriteLine($"\t\t\t}}");
							writer.WriteLine($"\t\t\tdataSize += {Marshal.SizeOf(elementType)} * {field.Name}.Length;");
						}
					} else if(elementType.IsEnum) {
						writer.WriteLine($"\t\t\tfor(int i = 0; i < {field.Name}.Length; ++i) {{");
						writer.WriteLine($"\t\t\t\twriter.Write((int){field.Name}[i]);");
						writer.WriteLine($"\t\t\t}}");
						writer.WriteLine($"\t\t\tdataSize += {sizeof(int)} * {field.Name}.Length;");
					}
					else if(typeof(Parcelable).IsAssignableFrom(elementType)) {
						writer.WriteLine($"\t\t\tfor(int i = 0; i < {field.Name}.Length; ++i) {{");
						writer.WriteLine($"\t\t\t\t{field.Name}[i].AppendToBytes(writer, out int dataSizeOf{field.Name}, encoding);");
						writer.WriteLine($"\t\t\t\tdataSize += dataSizeOf{field.Name};");
						writer.WriteLine($"\t\t\t}}");
					}
				} else if (fieldType == typeof(string)) {
					writer.WriteLine($"\t\t\t{{");
					writer.WriteLine($"\t\t\t\tbyte[] bytes = encoding.GetBytes({field.Name});");
					writer.WriteLine($"\t\t\t\twriter.Write(bytes.Length);");
					writer.WriteLine($"\t\t\t\twriter.Write(bytes);");
					writer.WriteLine($"\t\t\t\tdataSize += bytes.Length + {sizeof(int)};");
					writer.WriteLine($"\t\t\t}}");
				} else if(fieldType.IsPrimitive) {
					if(
						fieldType == typeof(bool) ||
						fieldType == typeof(int) ||
						fieldType == typeof(uint) || 
						fieldType == typeof(long) ||
						fieldType == typeof(ulong) ||
						fieldType == typeof(double) ||
						fieldType == typeof(float)
					) {
						writer.WriteLine($"\t\t\twriter.Write({field.Name});");
						writer.WriteLine($"\t\t\tdataSize += {Marshal.SizeOf(fieldType)};");
					}
				} else if(fieldType.IsEnum) {
					writer.WriteLine($"\t\t\twriter.Write((int){field.Name});");
					writer.WriteLine($"\t\t\tdataSize += {sizeof(int)};");
				} else if(fieldType.GetCustomAttribute<Parcelize>() != null) {
					writer.WriteLine($"\t\t\t{field.Name}.AppendToBytes(writer, out int dataSizeOf{field.Name}, encoding);");
					writer.WriteLine($"\t\t\tdataSize += dataSizeOf{field.Name};");
				}
			}
			writer.WriteLine($"\t\t}}");

			writer.WriteLine($"\t}}");
			writer.WriteLine($"}}");
		}

		private static void WriteTable(StreamWriter writer, System.Type type) {
			writer.WriteLine($"// Auto-generated by `ParcelableGenerator.GenerateTable()`");
			writer.WriteLine();
			writer.WriteLine($"using com.hexengine.gear.parameters.editor;");
			writer.WriteLine();
			writer.WriteLine($"namespace {type.Namespace}.editor {{");
			writer.WriteLine($"\tpublic sealed class {type.Name}Table : ParameterTable<{type.Name}> {{ }}");
			writer.WriteLine($"}}");
		}
	}
}