using System.Collections.Generic;
using System.IO;

namespace com.hexengine.gear.animation.editor {
	public static class AnimationControlGenerator {
		public static void Generate(
			StreamWriter writer,
			string ns,
			string className,
			int defaultPoseIndex,
			PoseParameterTable.BasePoseParameter[] basePoseParameters,
			PoseParameterTable.OverridePoseParameter[] overridePoseParameters,
			PoseParameterTable.AdditivePoseParameter[] additivePoseParameters
		) {
			writer.WriteLine($"// Auto Generated by AnimationControlGenerator.cs.");
			writer.WriteLine();
			writer.WriteLine($"using UnityEngine.Playables;");
			if(!ns.StartsWith(typeof(AnimationControlGraph).Namespace)) {
				writer.WriteLine($"using {typeof(AnimationControlGraph).Namespace};");
			}
			writer.WriteLine();
			writer.WriteLine($"namespace {ns} {{");
			writer.WriteLine($"\tpublic sealed class {className} : AnimationControlGraph {{");
			
			// properties
			writer.WriteLine($"\t\tpublic sealed class BasePoseControl {{");
			for(int i = 0; i < basePoseParameters.Length; ++i) {
				if(i != defaultPoseIndex) {
					writer.WriteLine($"\t\t\tpublic BasePoseParameter {basePoseParameters[i].name} = new BasePoseParameter {{");
					writer.WriteLine($"\t\t\t\tweight = {basePoseParameters[i].weight}f,");
					writer.WriteLine($"\t\t\t\tspeed = {basePoseParameters[i].speed},");
					writer.WriteLine($"\t\t\t}};");
				}
			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine($"\t\tprivate BasePoseControl _basePose = new BasePoseControl();");
			writer.WriteLine($"\t\tpublic BasePoseControl basePose => _basePose;");
			writer.WriteLine();

			writer.WriteLine($"\t\tpublic sealed class OverridePoseControl {{");
			for (int i = 0; i < overridePoseParameters.Length; ++i) {
				writer.WriteLine($"\t\t\tpublic OverridePoseParameter {overridePoseParameters[i].name} = new OverridePoseParameter {{");
				writer.WriteLine($"\t\t\t\tactive = { (overridePoseParameters[i].active ? "true" : "false") },");
				writer.WriteLine($"\t\t\t\tspeed = {overridePoseParameters[i].speed},");
				writer.WriteLine($"\t\t\t}};");
			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine($"\t\tprivate OverridePoseControl _overridePose = new OverridePoseControl();");
			writer.WriteLine($"\t\tpublic OverridePoseControl overridePose => _overridePose;");
			writer.WriteLine();

			writer.WriteLine($"\t\tpublic sealed class AdditivePoseControl {{");
			for (int i = 0; i < additivePoseParameters.Length; ++i) {
				writer.WriteLine($"\t\t\tpublic AdditivePoseParameter {additivePoseParameters[i].name} = new AdditivePoseParameter {{");
				writer.WriteLine($"\t\t\t\tweight = {additivePoseParameters[i].weight}f,");
				writer.WriteLine($"\t\t\t\tspeed = {additivePoseParameters[i].speed},");
				writer.WriteLine($"\t\t\t\tchanged = true,");
				writer.WriteLine($"\t\t\t}};");
			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine($"\t\tprivate AdditivePoseControl _additivePose = new AdditivePoseControl();");
			writer.WriteLine($"\t\tpublic AdditivePoseControl additivePose => _additivePose;");
			writer.WriteLine();

			// constructor
			writer.WriteLine($"\t\tpublic {className}(IAnimationClipSource clipSource) : base(");
			writer.WriteLine($"\t\t\tclipSource,");

			writer.WriteLine($"\t\t\tnew string[] {{");
			foreach(PoseParameterTable.BasePoseParameter basePoseParameter in basePoseParameters) {
				writer.WriteLine($"\t\t\t\t\"{basePoseParameter.clipName}\",");
			}
			writer.WriteLine($"\t\t\t}},");

			writer.WriteLine($"\t\t\tnew string[] {{");
			foreach(PoseParameterTable.OverridePoseParameter overridePoseParameter in overridePoseParameters) {
				writer.WriteLine($"\t\t\t\t\"{overridePoseParameter.clipName}\",");
			}
			writer.WriteLine($"\t\t\t}},");

			writer.WriteLine($"\t\t\tnew string[] {{");
			foreach(PoseParameterTable.AdditivePoseParameter additivePoseParameter in additivePoseParameters) {
				writer.WriteLine($"\t\t\t\t\"{additivePoseParameter.clipName}\",");
			}
			writer.WriteLine($"\t\t\t}}");

			writer.WriteLine($"\t\t) {{ }}");
			writer.WriteLine();

			// InitBasePose
			writer.WriteLine($"\t\tprotected override void InitBasePose(Playable playable) {{");
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			// InitOverridePose
			writer.WriteLine($"\t\tprotected override void InitOverridePose(Playable playable) {{");
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			// InitAdditivePose
			writer.WriteLine($"\t\tprotected override void InitAdditivePose(Playable playable) {{");
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			// UpdateBasePose
			List<string> basePoseNameList = new List<string>();
			foreach(PoseParameterTable.BasePoseParameter parameter in basePoseParameters) {
				basePoseNameList.Add(parameter.name);
			}
			basePoseNameList.RemoveAt(defaultPoseIndex);
			writer.WriteLine($"\t\tprotected override void UpdateBasePose(Playable playable) {{");
			if (basePoseParameters.Length > 0) {
				writer.WriteLine($"\t\t\tApplyBasePoseParameters(");
				if (basePoseParameters.Length > 1) {
					writer.WriteLine($"\t\t\t\t_basePose.{string.Join($",{System.Environment.NewLine}\t\t\t\t_basePose.", basePoseNameList)}");
				}
				writer.WriteLine($"\t\t\t);");

			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			// UpdateOverridePose
			writer.WriteLine($"\t\tprotected override void UpdateOverridePose(Playable playable) {{");
			if (overridePoseParameters.Length > 0) {
				List<string> overridePoseNameList = new List<string>();
				foreach (PoseParameterTable.OverridePoseParameter parameter in overridePoseParameters) {
					overridePoseNameList.Add(parameter.name);
				}
				writer.WriteLine($"\t\t\tApplyOverridePoseParameters(");
				writer.WriteLine($"\t\t\t\t_overridePose.{string.Join($",{System.Environment.NewLine}\t\t\t\t_overridePose.", overridePoseNameList)}");
				writer.WriteLine($"\t\t\t);");
			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			// UpdateAdditivePose
			writer.WriteLine($"\t\tprotected override void UpdateAdditivePose(Playable playable) {{");
			if(additivePoseParameters.Length > 0) {
				List<string> additivePoseNameList = new List<string>();
				foreach (PoseParameterTable.AdditivePoseParameter parameter in additivePoseParameters) {
					additivePoseNameList.Add(parameter.name);
				}
				writer.WriteLine($"\t\t\tApplyAdditivePoseParameters(");
				writer.WriteLine($"\t\t\t\t_additivePose.{string.Join($",{System.Environment.NewLine}\t\t\t\t_additivePose.", additivePoseNameList)}");
				writer.WriteLine($"\t\t\t);");
			}
			writer.WriteLine($"\t\t}}");
			writer.WriteLine();

			writer.WriteLine($"\t}}");
			writer.WriteLine($"}}");
		}
	}
}